modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT License"

[[mods]]
    modId="storagedelight"
    version="2024.07.23-1.21-forge"
    displayName="Storage Delight"
    authors="Axperty"
    description='''A mod that adds more storage options to the game.'''
    logoFile="assets/storagedelight/logo.png"

[[dependencies.storagedelight]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.storagedelight]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
