modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/axperty/storagedelight-forge/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL = "https://github.com/axperty/storagedelight-forge"
logoFile="logo.png"
logoBlur = false
authors="${mod_authors}"
description="A mod that adds more storage options to the game."

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"